actions:
  build:
    jobs:
      - build_and_test:
          runs-on: ruby:3.4
          name: Build and Test Apricity
          mounts:
            # Use DinD to allow apricity to test itself
            - source: /var/run/docker.sock
              target: /var/run/docker.sock
              type: bind
          steps:
            - name: Bundle install
              run: |
                bundle config set --local path 'vendor/bundle'
                bundle install

            # - name: Cache gems
            #   uses: apricity/cache
            #   with:
            #     key: bundler-${{ hashfiles('Gemfile.lock') }}
            #     path: vendor/bundle

            - name: Run tests
              run: |
                bundle exec rspec