name: Apricity Tests (Parallel)
actions:
  test:
    jobs:
      - lint:
          runs-on: ruby:3.4
          name: Lint Apricity Codebase
          mounts:
            - source: .
              target: /work
              type: bind
          steps:
            - name: Bundle install
              run: |
                bundle config set --local path 'vendor/bundle'
                bundle install
            - name: Run linters
              run: |
                bundle exec rubocop lib
      - test:
          runs-on: ruby:3.4
          name: Test Job Matrix
          needs: [lint]
          strategy:
            matrix:
              shard: [1, 2, 3, 4]
          mounts:
            - source: .
              target: /work
              type: bind
            # Use DinD to allow apricity to test itself
            - source: /var/run/docker.sock
              target: /var/run/docker.sock
              type: bind
          plugins:
            - uses: apricity/junit-reporter
              with:
                junit_reports: rspec-*.xml
                artifact_key: test-outputs
            - uses: apricity/simplecov-reporter
              with:
                coverage_report: .resultset.json
                artifact_key: coverage
          outputs:
            - key: test-outputs
              type: artifact
            - key: coverage
              type: artifact
          steps:
            - name: Display Matrix Env Vars
              run: |
                export | grep MATRIX
                echo "env matrix shard is: $MATRIX_SHARD/$MATRIX_TOTAL"
            - name: Bundle install
              run: |
                bundle config set --local path 'vendor/bundle'
                bundle install
            - name: Run tests
              run: |
                export PARALLEL_TEST_GROUPS=$MATRIX_TOTAL
                export PARALLEL_TEST_GROUP=$MATRIX_SHARD

                bundle exec parallel_rspec spec --only-group $MATRIX_SHARD --verbose -n $MATRIX_TOTAL \
                  --test-options "--format progress --format RspecJunitFormatter --out artifacts/test-outputs/rspec-$MATRIX_SHARD.xml"
              
      - quality:
          runs-on: ruby:3.4
          name: Check Apricity Code Quality
          needs: [test]
          mounts:
            - source: .
              target: /work
              type: bind
          steps:
            - name: Bundle install
              run: |
                bundle config set --local path 'vendor/bundle'
                bundle install

            - name: Run code quality tools
              run: |
                bundle exec reek lib
      - sbom:
          runs-on: ruby:3.4
          name: Generate SBOM for Apricity
          needs: [quality]
          plugins:
            - uses: apricity/sbom-reporter
              with:
                output_file: sbom.json
                artifact_key: sbom
          mounts:
            - source: .
              target: /work
              type: bind
          steps:
            - name: Bundle install
              run: |
                bundle config set --local path 'vendor/bundle'
                bundle install
            - name: Generate SBOM
              run: |
                bundle exec cyclonedx-ruby -o artifacts/sbom/sbom.xml -p .
          outputs:
            - key: sbom
              type: artifact