AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**'
    - 'example/**/*'
    - 'vendor/**/*'

plugins:
  - rubocop-rspec
  - rubocop-performance

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Exclude spec
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'