# fly.toml app configuration file generated for apricity-little-sun-6030 on 2026-01-16T10:24:54-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'apricity-ci'
primary_region = 'iad'

[build]

[env]
  APRICITY_ARTIFACT_ROOT = '/data/artifacts'
  APRICITY_CACHE_ROOT = '/data/cache'
  APRICITY_DOCKER_READ_TIMEOUT = 4800
  APRICITY_WORKER_CONCURRENCY = 2
  DOCKER_API_VERSION = '1.43'
  DOCKER_VERSION = '1.43'
  DOCKER_HOST = 'tcp://docker-for-kurt-delicate-pine-8745.internal:2375'
  PORT = '8080'
  RACK_ENV = 'production'
  BUNDLE_DEPLOYMENT = "true"
  BUNDLE_WITHOUT = "development:test"
  BUNDLE_PATH = "/usr/local/bundle"
  HOME = "/home/ruby"
  REDIS_URL = "redis://default:5b4adf48cfae41678708ca6937049984@fly-apricity-redis.upstash.io:6379"

[[mounts]]
  source = 'data'
  destination = '/data'
  
[http_service]
  internal_port = 8080
  processes = ["web"]
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2

[processes]
  web = "bundle exec foreman start"