require "active_record"
require "active_record/schema_migration"
require "active_record/internal_metadata"
require "yaml"
require "uri"
require_relative "config/environment"


namespace :db do
  db_config = if ENV["DATABASE_URL"]
                Environment.db_config_from_env
              else
                YAML.load_file("config/database.yml")
              end

  db_config_admin = if ENV["DATABASE_URL"]
                      # ENV["DATABASE_URL"]
                      admin_config = Environment.db_config_from_env.dup
                      admin_config['database'] = 'postgres'
                      admin_config['username'] = ENV['POSTGRES_USER'] if ENV['POSTGRES_USER']
                      admin_config['password'] = ENV['POSTGRES_PASSWORD'] if ENV['POSTGRES_PASSWORD']
                      admin_config
                    else
                      db_config.merge({'database' => 'postgres', 'schema_search_path' => 'public'})
                    end

  desc "Create the database"
  task :create do
    ActiveRecord::Base.establish_connection(db_config_admin)
    ActiveRecord::Base.connection.create_database(
      ENV.fetch("POSTGRES_DB") { raise "POSTGRES_DB not set" }
    )
    puts "Database created."
  end

  desc "Migrate the database"
  task :migrate do
    ActiveRecord::Base.establish_connection(db_config)
    pool = ActiveRecord::Base.connection_pool

    pool.schema_migration.create_table
    pool.internal_metadata.create_table

    ActiveRecord::MigrationContext
      .new("db/migrate", pool.schema_migration)
      .migrate

    puts "Database migrated."
  end

  desc "Drop the database"
  task :drop do
    ActiveRecord::Base.establish_connection(db_config_admin)
    ActiveRecord::Base.connection.drop_database(db_config["database"])
    puts "Database deleted."
  end

  desc "Reset the database"
  task :reset => [:drop, :create, :migrate]

  desc 'Create a db/schema.rb file that is portable against any DB supported by AR'
  task :schema do
    ActiveRecord::Base.establish_connection(db_config)
    require 'active_record/schema_dumper'
    filename = "db/schema.rb"
    File.open(filename, "w:utf-8") do |file|
      ActiveRecord::SchemaDumper.dump(ActiveRecord::Base.connection, file)
    end
  end

end

namespace :g do
  desc "Generate migration"
  task :migration do
    name = ARGV[1] || raise("Specify name: rake g:migration your_migration")
    timestamp = Time.now.strftime("%Y%m%d%H%M%S")
    path = File.expand_path("../db/migrate/#{timestamp}_#{name}.rb", __FILE__)
    migration_class = name.split("_").map(&:capitalize).join

    File.open(path, 'w') do |file|
      file.write <<-EOF
class #{migration_class} < ActiveRecord::Migration[7.1]

  def change
    # add your migration code here
  end

end
      EOF
    end

    puts "Migration #{path} created"
    abort # needed stop other tasks
  end
end